/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as UsecasesRouteImport } from './../routes/usecases'
import { Route as MeetingsRouteImport } from './../routes/meetings'
import { Route as MailRouteImport } from './../routes/mail'
import { Route as BoardRouteImport } from './../routes/board'
import { Route as IndexRouteImport } from './../routes/index'

const UsecasesRoute = UsecasesRouteImport.update({
  id: '/usecases',
  path: '/usecases',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/mail': typeof MailRoute
  '/meetings': typeof MeetingsRoute
  '/usecases': typeof UsecasesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/mail': typeof MailRoute
  '/meetings': typeof MeetingsRoute
  '/usecases': typeof UsecasesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/mail': typeof MailRoute
  '/meetings': typeof MeetingsRoute
  '/usecases': typeof UsecasesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/board' | '/mail' | '/meetings' | '/usecases'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/board' | '/mail' | '/meetings' | '/usecases'
  id: '__root__' | '/' | '/board' | '/mail' | '/meetings' | '/usecases'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRoute
  MailRoute: typeof MailRoute
  MeetingsRoute: typeof MeetingsRoute
  UsecasesRoute: typeof UsecasesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usecases': {
      id: '/usecases'
      path: '/usecases'
      fullPath: '/usecases'
      preLoaderRoute: typeof UsecasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRoute,
  MailRoute: MailRoute,
  MeetingsRoute: MeetingsRoute,
  UsecasesRoute: UsecasesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
